# Generated by Django 2.2.5 on 2019-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CM', 'Café da Manhã'), ('AL', 'Almoço'), ('LC', 'Lanche da Tarde'), ('JT', 'Janta')], max_length=1)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
