# Generated by Django 2.2.5 on 2019-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=50)),
                ('conteudo', models.CharField(max_length=350)),
                ('tipo', models.CharField(choices=[('PV', 'Prova'), ('TP', 'Trabalho Prático'), ('SM', 'Seminário')], max_length=1)),
            ],
        ),
    ]
