# Generated by Django 2.2.5 on 2019-10-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0005_auto_20191008_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifcApi.Representante'),
        ),
    ]
