# Generated by Django 2.2.5 on 2019-10-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0008_avaliacoes_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacoes',
            name='representante',
        ),
    ]
