# Generated by Django 2.2.5 on 2019-10-23 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0009_remove_avaliacoes_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacoes',
            name='adicionado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
