# Generated by Django 2.2.5 on 2019-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0010_avaliacoes_adicionado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('RP', 'Representante'), ('VR', 'Vice-Representante')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
