# Generated by Django 2.2.5 on 2019-10-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifcApi', '0011_auto_20191026_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifcApi.Turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='representante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifcApi.Representante'),
        ),
        migrations.AddField(
            model_name='turma',
            name='vice_representante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifcApi.Vice'),
        ),
    ]
